import { throwMovedAgentNativeModule } from "../../package-lifecycle/upgrade-error.js";

throwMovedAgentNativeModule(
  "@agent-native/core/client/chat",
  "@agent-native/core/client/agent-chat",
  {
    AGENT_PROMPT_MAX_INLINE_IMAGE_BYTES: "@agent-native/toolkit/app/chat",
    AGENT_PROMPT_MAX_INLINE_TEXT_CHARS: "@agent-native/toolkit/app/chat",
    AgentComposerFrame: "@agent-native/toolkit/app/chat",
    AgentComposerFrameProps: "@agent-native/toolkit/app/chat",
    AgentComposerLayoutVariant: "@agent-native/toolkit/app/chat",
    AgentPromptAttachment: "@agent-native/toolkit/app/chat",
    ComposerSubmitIntent: "@agent-native/toolkit/app/chat",
    FileReference: "@agent-native/toolkit/app/chat",
    FileResult: "@agent-native/toolkit/app/chat",
    MentionItem: "@agent-native/toolkit/app/chat",
    MentionPopover: "@agent-native/toolkit/app/chat",
    MentionReference: "@agent-native/toolkit/app/chat",
    PromptComposer: "@agent-native/toolkit/app/chat",
    PromptComposerFile: "@agent-native/toolkit/app/chat",
    PromptComposerProps: "@agent-native/toolkit/app/chat",
    PromptComposerSubmitOptions: "@agent-native/toolkit/app/chat",
    ReadAgentPromptAttachmentOptions: "@agent-native/toolkit/app/chat",
    RealtimeVoiceModeApi: "@agent-native/toolkit/app/chat",
    RealtimeVoiceModeBoundary: "@agent-native/toolkit/app/chat",
    RealtimeVoiceModeCopy: "@agent-native/toolkit/app/chat",
    RealtimeVoiceModeDock: "@agent-native/toolkit/app/chat",
    RealtimeVoiceModeDockProps: "@agent-native/toolkit/app/chat",
    RealtimeVoiceModeEntry: "@agent-native/toolkit/app/chat",
    RealtimeVoiceModeEntryProps: "@agent-native/toolkit/app/chat",
    RealtimeVoiceModeInlineSettings: "@agent-native/toolkit/app/chat",
    RealtimeVoiceModeProvider: "@agent-native/toolkit/app/chat",
    RealtimeVoiceModeProviderProps: "@agent-native/toolkit/app/chat",
    RealtimeVoiceModeSelectSetting: "@agent-native/toolkit/app/chat",
    RealtimeVoiceModeSettingOption: "@agent-native/toolkit/app/chat",
    RealtimeVoiceModeState: "@agent-native/toolkit/app/chat",
    RealtimeVoiceSessionAnswer: "@agent-native/toolkit/app/chat",
    RealtimeVoiceToolResult: "@agent-native/toolkit/app/chat",
    Reference: "@agent-native/toolkit/app/chat",
    SkillReference: "@agent-native/toolkit/app/chat",
    SkillResult: "@agent-native/toolkit/app/chat",
    SlashCommand: "@agent-native/toolkit/app/chat",
    TiptapComposer: "@agent-native/toolkit/app/chat",
    TiptapComposerHandle: "@agent-native/toolkit/app/chat",
    TiptapComposerProps: "@agent-native/toolkit/app/chat",
    TiptapComposerSubmitOptions: "@agent-native/toolkit/app/chat",
    canSubmitComposerContent: "@agent-native/toolkit/app/chat",
    createRealtimeVoiceSession: "@agent-native/toolkit/app/chat",
    createRealtimeVoiceSessionWithCapability: "@agent-native/toolkit/app/chat",
    displayableComposerModeMessage: "@agent-native/toolkit/app/chat",
    escapePromptAttachmentAttribute: "@agent-native/toolkit/app/chat",
    executeRealtimeVoiceTool: "@agent-native/toolkit/app/chat",
    extractRealtimeVoiceFunctionCalls: "@agent-native/toolkit/app/chat",
    formatPromptWithAttachments: "@agent-native/toolkit/app/chat",
    getComposerSubmitIntentForEnterKey: "@agent-native/toolkit/app/chat",
    handleComposerFileDrop: "@agent-native/toolkit/app/chat",
    insertComposerHardBreakAndScrollIntoView: "@agent-native/toolkit/app/chat",
    isInlineableAgentPromptFile: "@agent-native/toolkit/app/chat",
    readAgentPromptAttachment: "@agent-native/toolkit/app/chat",
    readRealtimeVoiceContext: "@agent-native/toolkit/app/chat",
    useMentionSearch: "@agent-native/toolkit/app/chat",
    useRealtimeVoiceMode: "@agent-native/toolkit/app/chat",
    useRealtimeVoiceModeCopy: "@agent-native/toolkit/app/chat",
    useRealtimeVoiceModeOptional: "@agent-native/toolkit/app/chat",
    ActionCard: "@agent-native/toolkit/app/chat",
  },
);
